config:
  credentials: []
  project_repos:
    github.com/CMCC-Foundation/ml-tropical-cyclones-detection:
      branch: main
      repo: https://github.com/CMCC-Foundation/ml-tropical-cyclones-detection
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-jade-cougar.sh
        container: qc.acc_sleepy-orchid-cassowary
  QC.Doc:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-ochre-sloth.sh
        container: qc.doc_homey-olive-hippopotamus
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-smalt-rabbit.sh
        container: qc.doc_messy-cream-avocet
  QC.Lic:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-heliotrope-numbat.sh
        container: qc.lic_hilly-green-bird
  QC.Ver:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-jade-whale.sh
        container: qc.ver_wiggy-tomato-warthog
timeout: 5400
