config:
  credentials: []
  project_repos:
    github.com/CMCC-Foundation/ml-tropical-cyclones-detection:
      branch: main
      repo: https://github.com/CMCC-Foundation/ml-tropical-cyclones-detection
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ecru-chicken.sh
        container: qc.acc_crabby-buff-iguana
  QC.Doc:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-lavender-gopher.sh
        container: qc.doc_pretty-heliotrope-zebra
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-dandelion-centipede.sh
        container: qc.doc_paltry-corn-warthog
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-lime-jellyfish.sh
        container: qc.doc_bumpy-ochre-crab
  QC.Lic:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-puce-magpie.sh
        container: qc.lic_messy-persimmon-fousek
  QC.Sec:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-maroon-buffalo.sh
        container: qc.sec_squeaky-yellow-jackal
  QC.Sty:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-platinum-ibis.sh
        container: qc.sty_sickly-flax-harrier
  QC.Uni:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-seashell-horse.sh
        container: qc.uni_scummy-harlequin-hyena
  QC.Ver:
    repos:
      github.com/CMCC-Foundation/ml-tropical-cyclones-detection get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-magnolia-baboon.sh
        container: qc.ver_hilly-eggplant-cuttlefish
timeout: 5400
